first review
Victor-Stepanov/stellar-burgers pull request #4
Opened 2022-05-25 17:32 UTC by Victor-Stepanov

2022-05-25 20:21 UTC, kyzinatra commented on src/utils/api.js
> +        })
Надо исправить: всеже стоит сюда передавать все ингредиенты что есть в constructor

2022-05-25 20:21 UTC, kyzinatra commented on src/utils/api.js
Отлично! Хорошая обработка ошибок

2022-05-25 20:28 UTC, kyzinatra commented on src/components/burger-constructor/burger-constructor.jsx
>      })
Можно лучше: будет круто, если обернуть эту функции в `useMemo`. Так они будут выполняться только когда поменяется что-то во входных данных

Подробнее: https://ru.reactjs.org/docs/hooks-reference.html#usememo

2022-05-25 20:33 UTC, kyzinatra requested changes
Выглядит очень круто! Видно, что проделана большая работа.

Что важно исправить:

- Исправить создание заказа по клику `Оформить заказ`

Можно лучше:

- Папку .idea лучше вынести в .gitignore так как она не влиянет на запуск или сборку проекта, а является полностью локальной.
- файл `data.js` с `mock` датой уже не используется, можно его убрать
- Папку `сontext` лушче назвать `services` так как вскоре там будет не только контекст 
- Использовать `useMemo` в конструкторе

Что понравилось:

- Хорошая обработка ошибок (можно еще круче даже чем сейчас если выводить ошибки не в лог а пользователю на экран)
- Код написан аккуратно

Обратите внимание, что работа принимается только после исправления всех `«Надо исправить»`.

2022-05-25 20:39 UTC, Victor-Stepanov commented on src/components/burger-constructor/burger-constructor.jsx
>      })
А про какую именно функцию идёт речь ?😅

2022-05-25 20:45 UTC, kyzinatra commented on src/components/burger-constructor/burger-constructor.jsx
>      })
Про функцию которая наполняет res :D 
```js
const res = [];
    ingredients.map((item) => {
        if (item.type !== 'bun') res.push(item)
    })
```

Можно кстати переделать в 1 строку с помощью `.filter`

2022-05-25 21:05 UTC, kyzinatra commented on src/components/burger-constructor/burger-constructor.jsx
>      })
Попробуйте `**/.idea` должно сработать

2022-05-26 06:22 UTC, Victor-Stepanov commented on src/components/app/App.jsx
> +    useEffect(getOrderData, [])
`Хорошая обработка ошибок (можно еще круче даже чем сейчас если выводить ошибки не в лог а пользователю на экран) `

Имеется ввиду сделать модальное окно для ошибок и пробрасывать?
Или просто в alert😂

2022-05-26 06:39 UTC, kyzinatra commented on src/components/app/App.jsx
> +    useEffect(getOrderData, [])
В этом плане никакох строгих рекомендаций в спринте нет так что полет вашей фантазии)
Можете сделать `alert`, а можете к примеру всплывающим окном, как сделано в этой библиотеке (только качать ее не надо) Она очень много весит и не нужна для проекта)
https://mui.com/material-ui/react-snackbar/#customization

2022-05-26 17:08 UTC, Victor-Stepanov commented on src/utils/api.js
> +        })
Есть вопрос, по простому мне нужно просто захоркодить сюда все id?
Либо, есть какой-то более сложный вариант без хардкода?

2022-05-26 17:27 UTC, kyzinatra commented on src/utils/api.js
> +        })
Не совсем. По клику на кнопку `Оформить заказ` сюда нужно передавать id всех компонентов которые сейчас находятся в `constructor` (не забудьте, что порядок важет и булки у вас 2, 1 и последняя). Вы получаете номер заказа и выводите его пользователю

2022-05-26 18:41 UTC, kyzinatra commented
Поздравляю! Ваша работа принята.
Вы отлично потрудились.
Удачного дальнейшего обучения.

2022-05-26 18:44 UTC, Victor-Stepanov commented on src/utils/api.js
> +        })
```
<Button type="primary" onClick={()=> {
                     onClick();
                     getOrderData(id)
                 }}>Оформить заказ</Button>
```

Подскажите, это нормально или все же костыль?
Я не очень понимаю(

2022-05-26 19:09 UTC, kyzinatra commented on src/utils/api.js
> +        })
На вашем месте я бы создал 1 функцию что-то вроде e openOrderModal и там бы уже вызывал и функцию запроса к api, а после уже открывал, там же модальное окно.  И прокидывал уже эту функцию. 
Но на самом деле в будущем спринте вы изучите Redux и всё эти решения станут не такими актуальными так как всё будет происходить уже там. Всё смены состояний, и всё вызовы api и как таковой props Drilling (Прокидывание пропсов) будет уже не актуально

2022-06-14 17:51 UTC, closed without merging